server:
  port: 8888
spring:
  # 数据库
  datasource:
    url: jdbc:mysql://192.168.10.30:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
    username: workflow
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    database: 0
    host: 192.168.10.40
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 35
        min-idle: 5

mybatis-plus:
  global-config:
    db-config:
      table-prefix: sys_
  mapper-locations: classpath*:/mapper/*.xml

